### ISSUE TITLE
Multiple copies of React loaded. 

### ISSUE THREAD

**Issue by bloycey** [andrerpena/react-mde#45] opened 2017-11-07 22:26 UTC
Hi,

Firstly, I can't wait to use this functionality - It looks much simpler and cleaner than the other solutions out there.

Unfortunately I'm currently receiving the following error message:

![multiplereact](https://user-images.githubusercontent.com/20733264/32521130-11c098fc-c45e-11e7-926b-2144cfcc89bf.JPG)

When I check the sources tab it looks like I'm loading React 16 and you've got React 15.6 (I think) included as a dependency. 

Any clues on how to resolve this one?

**Comment by andrerpena** [comment] 2017-11-12 08:24
Thank you very much! I'll take a look into it.

**Comment by andrerpena** [comment] 2017-11-12 15:10
This might have been caused by the fact that I was wrongfully listing `prop-types` 15.6 as a peerDependency. If updating doesn't solve your problem I don't really know what to do :). This are the only peerDependencies now and the project has 0 dependencies

```
"peerDependencies": {
    "font-awesome": "^4.7.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "showdown": "^1.8.1"
  }
```

**Comment by andrerpena** [comment] 2017-11-12 15:10
Please, try updating to 1.0.2

**Comment by andrerpena** [comment] 2017-11-13 18:58
I just realized your comment was before I released the latest version. I'm closing it. Feel free to reopen if you continue to experience the problem

**Closed** 2017-11-13 19:00 UTC
