### ISSUE TITLE
Confusion of how to get All 3 sub components working together. 

### ISSUE THREAD

**Issue by daanishnasir** [andrerpena/react-mde#60] opened 2017-11-28 17:42 UTC
On Version 2 of React-mde. 

I have all 3 components showing. I'm just not sure how to go about connecting all 3 components to work together. Example : Clicking bold from ReactMdeToolbar component does not bold the text in ReactMdeTextArea component. And the text typed into ReactMdeTextArea component does not show up in the ReactMdePreview component. I'm sure there is something i'm missing here, like refs or something needed.

Example: 

```

  handleValueChange = value => {

    this.setState({
      reactMdeValue: value,
    });
  };

return(
        <ReactMdeToolbar 
          commands={ReactMdeCommands.getDefaultCommands()}   
          />

        <ReactMdeTextArea          
            rows= {this.props.rows}
            title= {this.props.title}
            style= {textareaStyle}
            placeholder= {this.props.placeholder}
            className = "textarea-input"
            value={this.state.reactMdeValue}
            onChange={this.handleValueChange}      
        />

        <ReactMdePreview />

)
```

**Comment by daanishnasir** [comment] 2017-11-28 19:01
Update:        
```
            <ReactMdePreview 
              markdown={this.state.reactMdeValue.text}
              />
```

Not sure how to connect the toolbar.

**Comment by andrerpena** [comment] 2017-11-29 10:28
So, the `ReactMde` component is so thin that its only purpose is to connect the 3 components together :)

You are missing an `onCommand={this.handleCommand}` on the `ReactMdeToolbar`.  Please take a look at https://github.com/andrerpena/react-mde/blob/master/src/ReactMde.tsx

...If you still can't get it working. Give me a shout and I'll help you.

**Comment by andrerpena** [comment] 2017-11-30 01:07
I'm closing this. Feel free to open if you have any trouble.

**Comment by toastsgithub** [comment] 2017-12-20 17:11
@andrerpena Hi andrerpena. ReactMde is a greate React Md component, I really love it, but today when I trying to layout the 3-sub components myself, I found that I have no idea how to set the `handleCommand` function for the ReactMdeToolbar component **(I checked out your source code, this function is setted by default if I use ReactMde directly, but when I use sub component I have to offer this function myself)**, should I write it myself? Or should I just copy this function from here (of course translate it from ts to js)?https://github.com/andrerpena/react-mde/blob/master/src/ReactMde.tsx

Could you  please give me some hint? Maybe a snippet about how to implement handleCommand

Really appreciate it !

**Comment by andrerpena** [comment] 2017-12-20 17:25
@toastsgithub , I appreciate your kind words.
I can help you. Can you please wait until this weekend when I'll be available?
I'm reopening this issue to help keeping tracking of it.

**Comment by toastsgithub** [comment] 2017-12-21 04:32
Yeah of course. It's my side-project, I have some other work to go in the coming 2~3 days, we can discuss this problem later this weekend. Thanks for reply again😄

**Comment by andrerpena** [comment] 2018-01-17 11:51
I have to appologize. I DID NOT ABANDON THIS PROJECT WHATSOEVER. The problem is that during the last 3 weeks I'm solely dedicated to moving from Brazil to Germany and I have lots of bureaucracy to solve, stuff to get sorted, people to visit.

I know react-mde still has it's inconsistencies and as soon as I settle in Berlin in the first week of February, I'll get back to it and solve. It's not just because I really like this project. It's also because I use it in other project and I need it to work 100%.

Thanks for your comprehension.

**Closed** 2018-04-22 15:51 UTC
