### ISSUE TITLE
Cursor jumps with pre-set value

### ISSUE THREAD

**Issue by Sexual** [andrerpena/react-mde#142] opened 2018-10-04 16:59 UTC
On load: [image](https://i.imgur.com/gg2c1sQ.png)
After focusing at the end of "test" and typing **one** "1" (two "1"s appear): [image](https://i.imgur.com/971A9LR.png)

The code used is the same as https://github.com/andrerpena/react-mde#using but without a markdown generator.

Have any ideas as to what might be causing this? If you delete everything in the area and then type anything, it works perfectly fine.

**Comment by andrerpena** [comment] 2018-10-04 19:07
Sorry for the problem. Given your screenshot, I'm assuming you're not using the 6.0.0-alpha.1. Unfortunately, I'm not maintaining the 5.8 version anymore.. because of time constraints. I hope you understand.

I tried reproducing the problem on 6.0.0-alpha.1 on Chrome and I could not. Please provide more information.

**Comment by Sexual** [comment] 2018-10-05 00:49
@andrerpena Nope, definitely using 6.0.0-alpha.1.
```
                            <ReactMde onChange={(value) => this.setState({value: value})}
                                      value={this.state.value}
                                      minEditorHeight={200}
                                      maxEditorHeight={200}
                                      minPreviewHeight={200}
                                      generateMarkdownPreview={markdown => Promise.resolve(markdown)}/>
```

Using react-router and redux.

**Comment by andrerpena** [comment] 2018-10-05 07:32
Thanks for the info. I'll try to reproduce and set up a CodeSandbox example.

**Comment by andrerpena** [comment] 2018-10-08 21:23
I could not reproduce but I have set up a demo: https://codesandbox.io/s/o5vpjwyp79
Can you please provide me with exact instructions on how to reproduce using the above link?
Thanks!

**Comment by shrmnk** [comment] 2018-11-07 23:29
Same thing happens here.

I'm using Preact, Preact-Compat and Preact-Router. No redux, so I think this issue might be preact-related.

**Comment by Sexual** [comment] 2018-11-19 14:04
@shrmnk Did you manage to find a workaround for this?

**Comment by shrmnk** [comment] 2018-11-20 02:29
@Sexual Unfortunately no. I ended up moving to other markdown editors

**Comment by andrerpena** [comment] 2019-03-06 20:47
This has been solved by 7.*

**Closed by andrerpena** 2019-03-06 20:47 UTC
