### ISSUE TITLE
Text is removed on button click if no text selected

### ISSUE THREAD

**Issue by dmr** [andrerpena/react-mde#11] opened 2017-01-11 02:29 UTC
I tried the demo and entered some text and clicked a button and the text I entered disappeared.
What am I doing wrong?

**Comment by andrerpena** [comment] 2017-01-11 03:16
Not sure if related but I just fixed a header bug that was introduced this morning.

I just tested everything now, both in the published and local demo and everything looks fine.

In case you experience this error again. Please open the console, print the error (if any) and feel free to reopen it.

I'm closing it because I think it might have been caused by a PR

**Comment by dmr** [comment] 2017-01-24 05:52
I think I can reproduce now what my usage mistake is: I clicked the "bold" etc buttons without selecting text.
Current behavior: Text is removed.
Expected Behavior: Maybe a standard text is inserted, i.e. "**bold**".

Am I the only one with this problem?

**Comment by andrerpena** [comment] 2017-01-24 12:51
It's not a usage mistake @dmr , it's actually broken.  I can't reproduce your problem on Chrome. I know the button bar is broken on firefox and I'll fix it #15. What is your browser and OS?

I'll investigate. I'll probably fix the Firefox issue this week.

**Comment by dmr** [comment] 2017-01-25 03:59
macOS 10.12.2 with Chrome Canary (Version 57)

**Comment by andrerpena** [comment] 2017-11-30 22:14
I think this problem has been fixed already. Please feel free to re-open if you still encounter this issue

**Closed by andrerpena** 2017-11-30 22:14 UTC

**Comment by dmr** [comment] 2017-12-01 08:07
Thank you, I'll test it
