### ISSUE TITLE
Cannot perform undo/redo once switching to preview

### ISSUE THREAD

**Issue by ankurnarkhede** [andrerpena/react-mde#212] opened 2020-01-23 05:53 UTC
Steps to reproduce:

1. Write any text in the editor.
2. Go to preview. You find something wrong and want to undo it.
3. Go back to edit mode and press Ctrl+Z. It won't work.

This issue is probably because of the textarea is replaced in the DOM, which erases the undo history for the textarea.

**Comment by andrerpena** [comment] 2020-02-07 20:57
I will fix now

**Comment by andrerpena** [comment] 2020-02-07 22:20
Fixed. Please reopen if you still find the problem

**Comment by ankurnarkhede** [comment] 2020-02-08 03:00
@andrerpena , as per I tried with react-mde v8.0.2, I still couldn't perform the undo, redo operations.

**Comment by andrerpena** [comment] 2020-02-08 12:21
@ankurnarkhede , here is a Codesandbox already updated with the 8.0.2, you can see you can undo: https://codesandbox.io/s/react-mde-latest-bm6p3

The problem was that I was destroying the `textarea` and recreating everytime you would switch the tabs. This was causing the state to be lost. After I saw your message, I thought something went wrong on the publishing part, but I confirmed everything was working on CodeSandbox

**Comment by ankurnarkhede** [comment] 2020-02-08 12:34
Thanks, @andrerpena.  The undo operation works fine now on 8.0.2.
It wasn't working for me earlier, I tried on Chrome, it worked! Seems it's not working on Firefox.

**Comment by andrerpena** [comment] 2020-02-08 12:39
@ankurnarkhede Thanks for the information. I will check out Firefox

**Comment by andrerpena** [comment] 2020-02-08 12:50
On Firefox, the Github editor also has a problem with undo after you switch to Preview, and also after you change the text through a command. Apparently, this is a known issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1220696

Because the goal of react-mde is to achieve feature parity with Github, I will not work on problems that also exist on the Github editor, assuming that, if the problem exists there as well, it is probably too complicated to solve.

I will close this issue and thank you for reporting

**Closed** 2020-02-08 12:50 UTC
Labels: bug
